plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id "dagger.hilt.android.plugin"
}

apply from : '../../library_dependency.gradle'
apply from : '../../default_config.gradle'

android {
    namespace 'com.ajiedwi.prototype.learnktorandsqldelight.feature.pokemon'
    compileSdk 34

    defaultConfig {
        minSdk 24

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.8"
    }
}

dependencies {

    // lifecycle
    implementation fragmentKtxLibrary
    implementation lifecycleRuntimeComposeLibrary

    //Dagger - Hilt
    implementation hiltLibrary
    kapt hiltDaggerKapt
    implementation hiltNavigationComposeLibrary

    // ui
    implementation systemUiControllerLibrary

    // compose
    implementation platform(composeBom)
    androidTestImplementation platform(composeBom)

    implementation composeMaterial3
    implementation composePreview
    debugImplementation debugComposePreview
    implementation activityCompose
    implementation composeWindowsSizeClass
    implementation composeNavigation
    implementation constraintJetpackLibrary

    // timber
    implementation timberLibrary

    // coil
    implementation coilLibrary

    implementation project(":core:data")
    implementation project(":core:component")
    implementation project(":common")

    implementation project(":data:pokemon")
}